### ISSUE TITLE
GUI size

### ISSUE THREAD

**Issue by NordicGamerFE** [IllgiLP/PackModeMenu#4]
Seems like the gui dont either like my screen size or gui size at large maybe the best action would be to lock a gui size while in this menu or something along these lines
![image](https://user-images.githubusercontent.com/18188155/102127843-4c64a400-3e4d-11eb-9b58-40f7e41ca042.png)
also you should link your github so it shows a issue button on your curseforge project

**Comment by Cornit** [comment]
Oh, well thank you for reporting this. It's my first mod, such issues can happen. 😄 
And also thank you for letting me know, that I'm able to put a issue-button on curseforge. I'm also new to that 😀
